### ISSUE TITLE
Sounds

### ISSUE THREAD

**Issue by kristianthrane** [PentiaLabs/LifeSocks#15]
Let me know when the improved socket infrastructure is ready and I can slip in the sexy sounds from saturday night ...

**Comment by Saturate** [comment]
You can still add them to the preloader.

You can also add some of them to the board, as the logic used for this is in the board.

**Comment by teltploek** [comment]
Basically you should be able to put a command to play sounds inside these methods in game.js:

```
semenStop: function (semen) {
    semen.sprite.animations.stop('move');
},
semenMove: function (semen) {
    semen.sprite.animations.play('move', frameRate, true);
},
semenSmack: function (semen) {
    var game = this;
    var anim = semen.sprite.animations.getAnimation('smack');

    anim.onComplete.add(function () {
        game.semenStop(semen);
        game.semenMove(semen);
    }, this);

    semen.sprite.animations.play('smack', 8, false);
},
semenSplat: function (ground, semen) {
    var anim = semen.sprite.animations.getAnimation('splat');

    this.semenStop(semen);

    anim.onComplete.add(function () {
        semen.sprite.kill();
    }, this);

    semen.sprite.animations.play('splat', frameRate, false, true);
},
```

**Comment by teltploek** [comment]
I'll provide some comments to them, so you can tell them apart.

**Comment by teltploek** [comment]
comments added

**Comment by kristianthrane** [comment]
I guess we want them to play on the controller - so we need to throw in some socket emit to be able to play the sounds on the controller (play.js). Agree?

**Comment by teltploek** [comment]
yes, but don't we also want them to play on the board?

**Comment by Saturate** [comment]
I vote for both! :-)

**Comment by teltploek** [comment]
:+1:

**Comment by kristianthrane** [comment]
Herlige minder, men det er på tide at få den ud af mit issues-feed :)

**Comment by teltploek** [comment]
Du kan bare fjerne den fra watch, @kristianthrane :-)
