### ISSUE TITLE
Game should support simultaneous played games

### ISSUE THREAD

**Issue by teltploek** [PentiaLabs/LifeSocks#18]
It should be possible to have different games running at once.

So: `/board/<guuid-1>/` and `/board/<guuid-2>/` should be able to run simultaneously without interferring with one another.

**Comment by Saturate** [comment]
This should more or less be fixed now.
However we might need a little changes to it.

`host/:game` will open a controller.
`host/board/:game` will open a board.

**Comment by teltploek** [comment]
I don't understand. What do we need to change?

**Comment by Saturate** [comment]
I was thinking the URL scheme could be better.

Like:

`host/:game` - Controller
`host/:game/board` - Board

This might be a little more clear, and I feel it's better. Maybe theres a even better way?

**Comment by teltploek** [comment]
seems cool
