### ISSUE TITLE
Improve spawnpoint generation and direction when spawning

### ISSUE THREAD

**Issue by Gansted** [PentiaLabs/LifeSocks#24]
Spawn positions are completely random and the sperm always points "north" when spawning

**Comment by Gansted** [comment]
Already did an attempt at this which seems to work. The board is divided into four quadrants and spawn points are generated within those quadrants such that the first player spawns in quadrant 0, the second player in quadrant 1 and so on (player 5 spawns in quadrant 0). 
The sperms is pointed away from the edges when spawning.

Needs to be tested if logic that prevents two spermatozons to spawn in the same positions works properly.

**Comment by teltploek** [comment]
Seems legit. I'll close this. Very nice work!
