### ISSUE TITLE
SVG assests

### ISSUE THREAD

**Issue by Saturate** [PentiaLabs/LifeSocks#25]
We could see some performance gains by switching to SVG. It's worth trying out.
- Is there performance gains?
- Does Phaser.io support this?

**Comment by teltploek** [comment]
![image](https://cloud.githubusercontent.com/assets/248851/6144111/8320af14-b1d3-11e4-9153-8fc659435e3c.png)

http://www.html5gamedevs.com/topic/5267-phaser-svg-files/

**Comment by Saturate** [comment]
Closing it then.
