### ISSUE TITLE
Don't let the host start the game without the server approving this.

### ISSUE THREAD

**Issue by Saturate** [PentiaLabs/LifeSocks#26]
Don't let the host start the game without the server approving this.

We need to wait for the event `gameStarted` and not just change state. The `gameStarted`event is the same as used by other controllers.

**Comment by teltploek** [comment]
Can you elaborate or draw some sort of simple flow chart of what you want? Then I'll do it later tonight.

**Comment by Saturate** [comment]
Should be easy to explain.

Right now when you press "start game" the controller shifts to play mode, even if the server does not start the game due to only one player being online.

It should wait for the server to respond back with the correct event, then change state.

**Comment by teltploek** [comment]
Alright. Let's do it like this:
- First and only player gets a "Oh my you're the first player - Waiting for other players"
- The players that join after the first player gets "Get ready - Waiting for host to start game"
- When other players join, first players screen changes to "Oh my you're the first player - [Start game]"

**Comment by teltploek** [comment]
Done
