### ISSUE TITLE
Hook result screen up so we can pick a winner

### ISSUE THREAD

**Issue by teltploek** [PentiaLabs/LifeSocks#27]
We need to decide and present a winner on the result screen when the game is over.

**Comment by teltploek** [comment]
I'll do this now

**Comment by teltploek** [comment]
I've finished it on the client side, and done some of it on the server side.

**Comment by teltploek** [comment]
I just realised that I'm a bit stuck here until @Saturate commits the changes he was doing friday. I'll wait for him - no rush :smile:

**Comment by Saturate** [comment]
Done, maybe! :-)

**Comment by teltploek** [comment]
So what are the new routes (all the old routes now starts a controller) - we should probably update the links in the readme.

**Comment by Saturate** [comment]
`http://localhost:3000/board/brian` will open the board, `http://localhost:3000/brian` will open the controller.

Maybe, we should make the urls another way?

**Comment by teltploek** [comment]
I found out. I think it's good this way!

I've just hooked the controller result screens up, and I'll do the board result screen now, and then I think we have a game!!!

**Comment by Saturate** [comment]
It is good, but what about this: https://github.com/PentiaLabs/LifeSocks/issues/18#issuecomment-74435735

I feel it's better and you can also have a game named board. Seems a little better :) But that's a minor detail.

Awesome work :+1:

**Comment by teltploek** [comment]
We did it:
![gamegame](https://cloud.githubusercontent.com/assets/248851/6205163/7bbb7a52-b565-11e4-93a9-a74d69f9eb60.gif)
