### ISSUE TITLE
Change from hashbang route to express routes

### ISSUE THREAD

**Issue by teltploek** [PentiaLabs/LifeSocks#37]
We should handle routing on the server. Change this.

**Comment by teltploek** [comment]
So to elaborate at bit on this:
Right now we're using hashbang urls for room allocation. This can prove to be a little bit of a bitch to work with (let alone debug), so maybe we should have a more persistent type of url-routing to ease our development. On a personal note, I think it's a prettier solution anyhow, although I understand perfectly why we've started with the hashbang approach.

**Comment by Saturate** [comment]
Fixed this, but would be nice with some instructions on how to join a game when no game are defined.
