### ISSUE TITLE
Lobby/ready-screen

### ISSUE THREAD

**Issue by teltploek** [PentiaLabs/LifeSocks#7]
We need the lobby screen where players can submit their readiness.

When that's in place we can draw all players to the playing board in the create method rather than in the update method which we're doing right now.

**Comment by Saturate** [comment]
I'll do the server side of this.

**Comment by teltploek** [comment]
So the server is basically done. We now need to hook controller screens up.
- First player should be the only one having the "you are the first player"-screen (well, duh!)
- Other players should have "waiting for players"-screen or something similar.

It would probably be cool to solve #13 a long with this.

**Comment by teltploek** [comment]
This is done.
