### ISSUE TITLE
Lobby screen character avatars

### ISSUE THREAD

**Issue by Saturate** [PentiaLabs/LifeSocks#9]
When a new player joins the lobby we need to show their avatar. Look at the picture below.

We can hardcode this with a setTimeout until the events are working correctly.

![lifesocks](https://cloud.githubusercontent.com/assets/453018/6105606/49891c08-b059-11e4-911c-73e7ec67654d.PNG)

**Comment by teltploek** [comment]
I've started solving this issue.

**Comment by Saturate** [comment]
Awesome :+1:

**Comment by Saturate** [comment]
We also need the same thing done for the gameover screen.

**Comment by teltploek** [comment]
Roger

**Comment by teltploek** [comment]
Which actually raises an interesting question: How do we reuse code between stages? Not necessarily something we need to fix now, but it would be nice to do properly at some point.

**Comment by teltploek** [comment]
Well this is done. I'll open a new issue concerning putting this together with the new server.
